### ISSUE TITLE
Importing doesn't work

### ISSUE THREAD

**Issue by pmazumder3927** [DavidNKraemer/Gym-Wordle#1]
Running
`pip install gym_wordle`
and
`import gym_wordle`
Results in a 'module not found'. The package correctly shows as installed under the associated instance of pip.
I suspect it has something to do with the setup; the distribution folders are installed, but not the actual gym_wordle folder
![image](https://user-images.githubusercontent.com/24500086/152717568-1e7f88ec-0b4b-4089-a274-18c162e27d5a.png)

**Comment by Pixelatory** [comment]
I'm having the same issue.

**Comment by DavidNKraemer** [comment]
I also noticed this, and am trying to figure out why it won't install correctly. An issue with `setup.py` I'm sure.

**Comment by Pixelatory** [comment]
Yeah most likely. I contributed to another repo that has wordle for gym working [here](https://github.com/zach-lawless/gym-wordle) if that helps.

**Comment by DavidNKraemer** [comment]
I believe I have solved this with the version 0.1.3 in the latest commit.
